version: "0.2"

branches:
  default:
    stage: "pre-merge"

stages:
  pre-merge:
    worker: &pod
      type: kube_pod
      path: eve/workers/zenko.yaml
      images:
        aggressor: eve/workers/aggressor
    steps:
    - TriggerStages:
        name: trigger all the examples
        stage_names:
        - access_cluster_1_8_8
        - access_cluster_1_9_6
        - non_existing_cluster
        - without_namespace

  access_cluster_1_9_6:
    worker:
      <<: *pod
      service:
        requests:
          version: "1.9.6"
        namespaces:
        - "mynamespace"    # <<< the default namespace for that stage
        - "mynamespace-2"
    steps:
    - ShellCommand:
        name: display server version
        command: kubectl version
    - ShellCommand:
        name: can access the default namespace (first in list)
        command: kubectl get pod
    - ShellCommand:
        name: can access the second namespace
        command: kubectl get pods --namespace %(prop:mynamespace-2)s
    - ShellCommand:
        name: cannot access other namespaces
        command: kubectl get pods --namespace default
    - ShellCommand:
        name: can create pods
        command: kubectl run my-nginx --image=nginx --replicas=2 --port=80
    - ShellCommand:
        name: list pods and deployment
        command: kubectl get pods && kubectl get deployment

  access_cluster_1_8_8:
    worker:
      <<: *pod
      service:
        requests:
          version: "1.8.8"
        namespaces:
        - "mynamespace"
    steps:
    - ShellCommand:
        name: display server version
        command: kubectl version
    - ShellCommand:
        name: run helm
        command: helm install

  non_existing_cluster:
    worker:
      <<: *pod
      service:
        requests:
          version: "1.6.3"
        namespaces:
        - "mynamespace"
    steps:
    - ShellCommand:
        name: will never run
        command: exit 1

  without_namespace:
    worker:
      <<: *pod
      service:
        requests:
          version: "1.8.8"
        #namespaces:
        #- "mynamespace"
    steps:
    - ShellCommand:
        name: run helm
        command: helm install
